benchmark_root: /media/rootalkhatib/My Passport/reda_ws/intern_ship_ws/assets/data/LIBERO/libero/libero
bddl_files: /media/rootalkhatib/My Passport/reda_ws/intern_ship_ws/assets/data/LIBERO/libero/libero/bddl_files
init_states: /media/rootalkhatib/My Passport/reda_ws/intern_ship_ws/assets/data/LIBERO/libero/libero/init_files
datasets: /media/rootalkhatib/My Passport/reda_ws/intern_ship_ws/assets/data/LIBERO/libero/libero/../datasets
assets: /media/rootalkhatib/My Passport/reda_ws/intern_ship_ws/assets/data/LIBERO/libero/libero/assets
