benchmark_root: /home/utilisateur/worldmodel/LIBERO-PRO/libero/libero
bddl_files: /home/utilisateur/worldmodel/LIBERO-PRO/libero/libero/bddl_files
init_states: /home/utilisateur/worldmodel/LIBERO-PRO/libero/libero/init_files
datasets: /home/utilisateur/worldmodel/LIBERO-PRO/libero/datasets
assets: /home/utilisateur/worldmodel/LIBERO-PRO/libero/libero/assets
